export const profiles = [
  {
    id: 1,
    name: "Davina",
    age: 23,
    location: "Abuja",
    matchPercentage: 85,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/davina-cover.svg",
    profileImage: "/davina.svg",
  },
  {
    id: 2,
    name: "Emily",
    age: 31,
    location: "Lagos",
    matchPercentage: 80,
    verified: false,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/emily-cover.svg",
    profileImage: "/emily.svg",
  },
  {
    id: 3,
    name: "John",
    age: 28,
    location: "Delta",
    matchPercentage: 72,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/john-cover.svg",
    profileImage: "/john.svg",
  },
  {
    id: 4,
    name: "Davina",
    age: 23,
    location: "Abuja",
    matchPercentage: 85,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/davina-cover.svg",
    profileImage: "/davina.svg",
  },
  {
    id: 5,
    name: "Emily",
    age: 31,
    location: "Lagos",
    matchPercentage: 80,
    verified: false,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/emily-cover.svg",
    profileImage: "/emily.svg",
  },
  {
    id: 6,
    name: "John",
    age: 28,
    location: "Delta",
    matchPercentage: 72,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/john-cover.svg",
    profileImage: "/john.svg",
  },
  {
    id: 7,
    name: "Davina",
    age: 23,
    location: "Abuja",
    matchPercentage: 85,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/davina-cover.svg",
    profileImage: "/davina.svg",
  },
  {
    id: 8,
    name: "Emily",
    age: 31,
    location: "Lagos",
    matchPercentage: 80,
    verified: false,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/emily-cover.svg",
    profileImage: "/emily.svg",
  },
  {
    id: 9,
    name: "John",
    age: 28,
    location: "Delta",
    matchPercentage: 72,
    verified: true,
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec. Integer pretium orci nec nulla pellentesque pretium.",
    coverImage: "/john-cover.svg",
    profileImage: "/john.svg",
  },
];
